// Divya Health Care - Tests & Packages Catalog Data
// (Only real lab assets used: Taking test2.jpg, Taking test.jpg, arrangement.jpg, test photo.jpg)
const diagnosticData = {
  categories: [
    { id: 'all', name: 'All Tests', icon: 'fa-solid fa-list-check' },
    { id: 'full-body', name: 'Full Body', icon: 'fa-solid fa-person' },
    { id: 'blood', name: 'Blood Test', icon: 'fa-solid fa-droplet' },
    { id: 'thyroid', name: 'Thyroid', icon: 'fa-solid fa-shield-virus' },
    { id: 'diabetes', name: 'Diabetes', icon: 'fa-solid fa-cubes-stacked' },
    { id: 'vitamins', name: 'Vitamins', icon: 'fa-solid fa-capsules' },
    { id: 'fitness', name: 'Fitness & Gym', icon: 'fa-solid fa-dumbbell' },
    { id: 'heart', name: 'Heart Health', icon: 'fa-solid fa-heart-pulse' },
    { id: 'liver-kidney', name: 'Liver & Kidney', icon: 'fa-solid fa-stethoscope' }
  ],

  packages: [
    {
      id: 'full-body-health-checkup',
      name: 'Full Body Health Checkup',
      tagline: 'Essential tests for overall health and early detection',
      testCount: 18,
      category: 'full-body',
      price: 2500,
      originalPrice: 3500,
      discount: 1000,
      badge: 'Popular Checkup',
      image: 'Taking test2.jpg',
      isPopular: true,
      sampleType: 'Blood & Urine',
      fastingRequired: '10-12 Hours Fasting Required',
      reportTime: '12-24 Hours',
      featuredTags: ['CBC', 'LFT', 'KFT', 'Lipid Profile', '+14 more'],
      about: 'A comprehensive preventive health checkup package designed to assess vital organ functions including heart, liver, kidney, blood sugar, and general metabolic health for early risk detection.',
      testsIncluded: [
        'Complete Blood Count (CBC) - 24 parameters',
        'Fasting Blood Sugar (FBS)',
        'HbA1c (Glycated Hemoglobin - 3 Months Average)',
        'Lipid Profile (Cholesterol, HDL, LDL, Triglycerides, VLDL)',
        'Liver Function Test (LFT - Bilirubin, SGOT, SGPT, Alk Phos, Protein)',
        'Kidney Function Test (KFT - Urea, BUN, Creatinine, Uric Acid)',
        'Thyroid Profile (T3, T4, TSH)',
        'Vitamin B12 (Cyanocobalamin)',
        'Vitamin D (25-Hydroxy)',
        'C-Reactive Protein (CRP Quantitative)',
        'Iron Panel (Serum Iron, Total Iron Binding Capacity)',
        'Urine Routine & Microscopic Examination',
        'Serum Creatinine',
        'Serum Uric Acid',
        'Serum Electrolytes (Sodium, Potassium, Chloride)',
        'Serum Calcium',
        'Erythrocyte Sedimentation Rate (ESR)',
        'Doctor Tele-Consultation & Report Guidance'
      ],
      preparation: [
        'Overnight fasting of 10 to 12 hours is mandatory. Water is allowed.',
        'Avoid heavy fatty meals and alcohol 24 hours prior to sample collection.',
        'Morning first-void urine sample is recommended for the urine test.',
        'Consult your doctor if you take routine blood pressure or thyroid medications in the morning.'
      ]
    },
    {
      id: 'premium-full-body-checkup',
      name: 'Premium Full Body Checkup',
      tagline: 'A comprehensive health assessment for complete peace of mind',
      testCount: 28,
      category: 'full-body',
      price: 4200,
      originalPrice: 6000,
      discount: 1800,
      badge: 'Most Popular',
      image: 'Taking test.jpg',
      isPopular: true,
      sampleType: 'Blood & Urine',
      fastingRequired: '10-12 Hours Fasting Required',
      reportTime: 'Same Day / 24 Hours',
      featuredTags: ['Includes CBC', 'KFT', 'LFT', 'Thyroid', '+24 more'],
      about: 'Our most comprehensive head-to-toe screening package including extensive cardiac markers, micronutrients, pancreatic enzymes, arthritis markers, and detailed metabolic profiles for adults and senior members.',
      testsIncluded: [
        'Complete Blood Count with ESR (CBC + ESR 28 parameters)',
        'Fasting Blood Glucose (FBS)',
        'HbA1c with Estimated Average Glucose (eAG)',
        'Comprehensive Lipid Profile (Total, HDL, LDL, VLDL, Non-HDL, Ratio)',
        'Extended Liver Function Test (LFT with Albumin/Globulin ratio)',
        'Comprehensive Kidney Function Test (KFT with eGFR calculation)',
        'Ultra-Sensitive Thyroid Panel (FT3, FT4, Ultrasensitive TSH)',
        'High Sensitivity C-Reactive Protein (hs-CRP Cardiac Risk)',
        'Serum Ferritin & Total Iron Panel (TIBC & Transferrin Saturation)',
        'Vitamin D3 (25-OH Cholecalciferol)',
        'Vitamin B12 (Active Cobalamin)',
        'Folic Acid (Vitamin B9)',
        'Serum Calcium & Inorganic Phosphorus',
        'Serum Magnesium',
        'Serum Electrolytes (Na, K, Cl, Bicarbonate)',
        'Uric Acid (Gout screening)',
        'Serum Amylase & Lipase (Pancreatic Health)',
        'Rheumatoid Factor (RA Factor Qualitative)',
        'Urine Complete Examination (Chemical & Microscopic)',
        'Urine Microalbumin/Creatinine Ratio (Early Kidney Marker)',
        'Free Doctor Consultation & Medical Summary'
      ],
      preparation: [
        'Strict fasting of 10-12 hours required before morning collection.',
        'Drink plenty of plain water to stay well-hydrated for smooth phlebotomy.',
        'Avoid vigorous exercise on the morning of blood drawing.'
      ]
    },
    {
      id: 'gym-performance-profile',
      name: 'Gym Performance Profile',
      tagline: 'Ideal for fitness enthusiasts, bodybuilders, and active lifestyle',
      testCount: 15,
      category: 'fitness',
      price: 4599,
      originalPrice: 5620,
      discount: 1021,
      badge: 'Fitness Essential',
      image: 'arrangement.jpg',
      isPopular: true,
      sampleType: 'Blood Sample',
      fastingRequired: '8-10 Hours Fasting',
      reportTime: '24 Hours',
      featuredTags: ['Includes CBC', 'LFT', 'KFT', 'Vitamin D', '+11 more'],
      about: 'Tailored for athletes, fitness trainees, and gym-goers to monitor hormonal health, muscle damage enzymes, protein synthesis, organ safety (liver & kidney for supplement users), and micronutrients.',
      testsIncluded: [
        'Complete Blood Count (CBC) with Hemoglobin & RBC Indices',
        'Total Serum Testosterone',
        'Creatine Kinase / Phosphokinase (CPK - Muscle breakdown marker)',
        'Serum Cortisol (Stress & Recovery hormone)',
        'Comprehensive Liver Function Test (LFT)',
        'Renal / Kidney Function Test (KFT - Serum Creatinine & BUN)',
        'Lipid Profile (Cholesterol balance & Cardiovascular risk)',
        'Vitamin D3 (Bone strength & Muscle contraction)',
        'Vitamin B12 (Energy metabolism & Nerve function)',
        'Serum Uric Acid',
        'Serum Electrolytes (Sodium, Potassium, Chloride)',
        'Serum Calcium & Magnesium',
        'Fasting Blood Sugar (FBS)',
        'High Sensitivity CRP'
      ],
      preparation: [
        'Fast for 8 to 10 hours overnight.',
        'Avoid heavy strength training or strenuous workout 24 hours prior (prevents temporary spikes in CPK and liver enzymes).',
        'Collect sample in morning (best for peak testosterone measurement).'
      ]
    },
    {
      id: 'diabetes-care-package',
      name: 'Diabetes Care Package',
      tagline: 'Complete sugar control and diabetic organ protection package',
      testCount: 12,
      category: 'diabetes',
      price: 1750,
      originalPrice: 2500,
      discount: 750,
      badge: 'Specialized',
      image: 'test photo.jpg',
      isPopular: false,
      sampleType: 'Blood & Urine',
      fastingRequired: 'Fasting + Post Prandial (PP)',
      reportTime: 'Same Day',
      featuredTags: ['HbA1c', 'FBS', 'PPBS', 'Lipid', 'Urine Microalbumin'],
      about: 'Designed for diabetic and pre-diabetic patients to track 90-day glycemic control, kidney filtration risk, microvascular changes, and cholesterol health.',
      testsIncluded: [
        'Fasting Blood Glucose (FBS)',
        'Post Prandial Blood Glucose (PPBS - 2 hours post meal)',
        'HbA1c (Glycosylated Hemoglobin)',
        'Estimated Average Glucose (eAG)',
        'Complete Lipid Profile',
        'Serum Creatinine & Blood Urea Nitrogen',
        'Urine Microalbumin to Creatinine Ratio',
        'Urine Routine & Microscopic Test',
        'Complete Blood Count (CBC)'
      ],
      preparation: [
        'Fasting sample requires 8-10 hours overnight fast.',
        'Post prandial sample is taken exactly 2 hours after your meal.'
      ]
    },
    {
      id: 'cardiac-risk-profile',
      name: 'Heart Health & Cardiac Risk Profile',
      tagline: 'Early detection of coronary risk, cholesterol plaque & inflammation',
      testCount: 14,
      category: 'heart',
      price: 2999,
      originalPrice: 4200,
      discount: 1201,
      badge: 'Cardio Care',
      image: 'arrangement.jpg',
      isPopular: false,
      sampleType: 'Blood Sample',
      fastingRequired: '12 Hours Fasting',
      reportTime: '24 Hours',
      featuredTags: ['hs-CRP', 'Lipid Profile', 'Homocysteine', 'ApoA1', 'ApoB'],
      about: 'Advanced cardiovascular screening assessing lipid fractions, arterial wall inflammation, homocysteine levels, and metabolic indicators that predict cardiovascular disease.',
      testsIncluded: [
        'Advanced Lipid Profile (Direct LDL, HDL, Triglycerides, VLDL)',
        'High-Sensitivity C-Reactive Protein (hs-CRP)',
        'Serum Homocysteine',
        'Apolipoprotein A1 (Apo-A1)',
        'Apolipoprotein B (Apo-B)',
        'Apo B / Apo A1 Ratio',
        'HbA1c & Fasting Blood Sugar',
        'Complete Blood Count (CBC)',
        'Kidney Function Test (KFT)',
        'Serum Electrolytes'
      ],
      preparation: [
        '12 hours overnight fasting mandatory. No alcohol for 48 hours prior.'
      ]
    },
    {
      id: 'women-wellness-package',
      name: 'Women Wellness & Hormone Package',
      tagline: 'Focused screening for PCOS, thyroid, bone density & anemia in women',
      testCount: 22,
      category: 'full-body',
      price: 3200,
      originalPrice: 4500,
      discount: 1300,
      badge: "Women's Health",
      image: 'test photo.jpg',
      isPopular: false,
      sampleType: 'Blood & Urine',
      fastingRequired: '10-12 Hours Fasting',
      reportTime: '24 Hours',
      featuredTags: ['Thyroid', 'Iron Panel', 'Vitamin D3', 'B12', 'CBC', 'Calcium'],
      about: 'Specially created for women across all age groups addressing common issues like unexplained fatigue, hair fall, hormonal imbalance, thyroid irregularity, calcium depletion, and iron deficiency.',
      testsIncluded: [
        'Complete Blood Count with Anemia indices',
        'Complete Iron Profile (Serum Iron, Ferritin, TIBC)',
        'Thyroid Profile (Total T3, T4, TSH)',
        'Vitamin D3 (Cholecalciferol)',
        'Vitamin B12',
        'Serum Calcium & Phosphorus',
        'Liver Function Test (LFT)',
        'Kidney Function Test (KFT)',
        'Fasting Blood Sugar',
        'Lipid Profile',
        'Urine Routine & Microscopic'
      ],
      preparation: [
        '10-12 hours overnight fast. Avoid taking iron supplements on testing morning.'
      ]
    },
    {
      id: 'monsoon-fever-profile',
      name: 'Fever / Infection Rapid Screening',
      tagline: 'Quick diagnostic panel for unexplained fever, dengue, malaria & typhoid',
      testCount: 9,
      category: 'blood',
      price: 1499,
      originalPrice: 2200,
      discount: 701,
      badge: 'Rapid 6-Hour',
      image: 'arrangement.jpg',
      isPopular: false,
      sampleType: 'Blood & Urine',
      fastingRequired: 'No Fasting Required',
      reportTime: '6-8 Hours Rapid Delivery',
      featuredTags: ['Dengue NS1', 'Platelet Count', 'Widal', 'Malaria', 'CBC'],
      about: 'Rapid multi-pathogen screening protocol for patients suffering from acute fever, chills, body ache, or weakness. Emergency rapid home collection available.',
      testsIncluded: [
        'Complete Blood Count with Platelet Count (CBC + Platelets)',
        'Dengue Virus NS1 Antigen (Rapid)',
        'Dengue IgG & IgM Antibodies',
        'Widal Slide Agglutination (Typhoid Fever)',
        'Malarial Parasite Identification (Smear & Antigen)',
        'Urine Routine Examination (UTI Check)',
        'C-Reactive Protein (CRP)',
        'Liver Function Test (Bilirubin & SGPT)',
        'Serum Creatinine'
      ],
      preparation: [
        'No fasting required. Can be collected any time of day or night.'
      ]
    }
  ],

  individualTests: [
    {
      id: 'crp',
      name: 'CRP (C-Reactive Protein)',
      category: 'heart',
      price: 500,
      originalPrice: 600,
      reportTime: '4-6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Quantitative inflammation marker used to assess bacterial infections, inflammation, and autoimmune flares.'
    },
    {
      id: 'cbc',
      name: 'Complete Blood Count (CBC)',
      category: 'blood',
      price: 350,
      originalPrice: 450,
      reportTime: '4-6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Measures Hemoglobin, RBC, WBC count, Platelets, MCV, MCH, and Hematocrit for infection or anemia screening.'
    },
    {
      id: 'cbc-esr',
      name: 'CBC + ESR',
      category: 'blood',
      price: 400,
      originalPrice: 500,
      reportTime: '4-6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Complete Blood Count combined with Erythrocyte Sedimentation Rate to screen for infection or inflammation.'
    },
    {
      id: 'lft',
      name: 'Liver Function Test (LFT)',
      category: 'liver-kidney',
      price: 700,
      originalPrice: 800,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: '8-10 Hours Fasting',
      description: 'Comprehensive panel measuring Bilirubin, SGOT, SGPT, Alkaline Phosphatase, Total Protein, Albumin, and A:G ratio.'
    },
    {
      id: 'kft',
      name: 'Kidney Function Test (KFT / RFT)',
      category: 'liver-kidney',
      price: 700,
      originalPrice: 800,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Strict Fasting Required',
      description: 'Assesses renal health measuring Blood Urea, BUN, Serum Creatinine, Uric Acid, and estimated eGFR.'
    },
    {
      id: 'lipid-profile',
      name: 'Lipid Profile (Cholesterol Panel)',
      category: 'heart',
      price: 600,
      originalPrice: 700,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: '10-12 Hours Fasting',
      description: 'Full cholesterol panel including Total Cholesterol, HDL (good), LDL (bad), VLDL, and Triglycerides.'
    },
    {
      id: 'urine-rm',
      name: 'Urine Routine & Microscopic (Urine R/M)',
      category: 'liver-kidney',
      price: 100,
      originalPrice: 100,
      reportTime: '3-4 Hours',
      sampleType: 'Urine',
      fastingRequired: 'Morning First Void Recommended',
      description: 'Microscopic and chemical urinalysis for urinary tract infection, sugar, pus cells, and proteinuria.'
    },
    {
      id: 'fbs-rbs',
      name: 'FBS / RBS / RBSP (Blood Sugar)',
      category: 'diabetes',
      price: 70,
      originalPrice: 70,
      reportTime: '2-4 Hours',
      sampleType: 'Blood (Fluoride)',
      fastingRequired: 'Fasting / Random as advised',
      description: 'Fasting Blood Sugar, Random Blood Sugar, or Post-Prandial Glucose for rapid diabetic monitoring.'
    },
    {
      id: 'thyroid-profile',
      name: 'Thyroid Profile (T3, T4, TSH)',
      category: 'thyroid',
      price: 600,
      originalPrice: 700,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Evaluates Total Triiodothyronine (T3), Total Thyroxine (T4), and Thyroid Stimulating Hormone (TSH).'
    },
    {
      id: 'free-thyroid-profile',
      name: 'Free Thyroid Profile (FT3, FT4, TSH)',
      category: 'thyroid',
      price: 650,
      originalPrice: 750,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Measures unbound active Free T3 and Free T4 along with Ultrasensitive TSH for accurate hormone evaluation.'
    },
    {
      id: 'tsh',
      name: 'TSH (Thyroid Stimulating Hormone)',
      category: 'thyroid',
      price: 250,
      originalPrice: 350,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Ultrasensitive single-parameter screening for hypothyroidism, hyperthyroidism, and medication titration.'
    },
    {
      id: 'ft3-ft4-tsh',
      name: 'FT3, FT4, TSH Panel',
      category: 'thyroid',
      price: 600,
      originalPrice: 700,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Direct diagnostic assay of unbound Free Triiodothyronine, Free Thyroxine, and Ultrasensitive TSH.'
    },
    {
      id: 'tpo-anti-thyroperoxidase',
      name: 'TPO Anti Thyroperoxidase',
      category: 'thyroid',
      price: 1100,
      originalPrice: 1200,
      reportTime: '12-24 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Autoantibody marker used to identify autoimmune thyroid conditions like Hashimoto thyroiditis or Graves disease.'
    },
    {
      id: 'vitamin-b12',
      name: 'Vitamin B12 (Cyanocobalamin)',
      category: 'vitamins',
      price: 1100,
      originalPrice: 1200,
      reportTime: '8-12 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Measures active Cyanocobalamin for nerve health, neurological wellness, energy levels, and red blood cells.'
    },
    {
      id: 'vitamin-d',
      name: 'Vitamin D3 (25 OH Cholecalciferol)',
      category: 'vitamins',
      price: 1500,
      originalPrice: 1600,
      reportTime: '8-12 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Measures 25-Hydroxy Vitamin D for bone mineral density, joint strength, calcium metabolism, and immunity.'
    },
    {
      id: 'folic-acid',
      name: 'Folic Acid (Vitamin B9)',
      category: 'vitamins',
      price: 350,
      originalPrice: 450,
      reportTime: '8-12 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Evaluates Folate concentration crucial for healthy red cell formation, DNA repair, and prenatal care.'
    },
    {
      id: 'calcium',
      name: 'Serum Calcium',
      category: 'vitamins',
      price: 120,
      originalPrice: 120,
      reportTime: '4 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Measures total serum calcium level vital for bones, teeth, cardiac rhythm, and neuromuscular function.'
    },
    {
      id: 'urine-cs',
      name: 'Urine C/S (Culture & Sensitivity)',
      category: 'liver-kidney',
      price: 500,
      originalPrice: 600,
      reportTime: '48-72 Hours',
      sampleType: 'Urine (Sterile)',
      fastingRequired: 'Clean-catch Midstream Urine',
      description: 'Bacterial culture identifying specific UTI pathogens and testing susceptibility to targeted antibiotics.'
    },
    {
      id: 'urine-mau',
      name: 'Urine MAU (Microalbumin)',
      category: 'liver-kidney',
      price: 325,
      originalPrice: 425,
      reportTime: '4-6 Hours',
      sampleType: 'Urine',
      fastingRequired: 'Morning First Void Recommended',
      description: 'Detects microscopic albumin leakage in urine, crucial for early diabetic and hypertensive kidney disease detection.'
    },
    {
      id: 'microalbumin-creatinine-ratio',
      name: 'Microalbumin / Creatinine Ratio (ACR)',
      category: 'liver-kidney',
      price: 325,
      originalPrice: 425,
      reportTime: '4-6 Hours',
      sampleType: 'Urine',
      fastingRequired: 'Morning First Void Recommended',
      description: 'Spot urine albumin-to-creatinine ratio test, the international clinical standard for diabetic nephropathy screening.'
    },
    {
      id: 'ra-factor',
      name: 'RA Factor (Rheumatoid Arthritis Factor)',
      category: 'blood',
      price: 400,
      originalPrice: 500,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Diagnostic test for rheumatoid factor autoantibodies associated with joint inflammation and arthritis.'
    },
    {
      id: 'anti-ccp',
      name: 'Anti CCP (Early Arthritis Marker)',
      category: 'blood',
      price: 1500,
      originalPrice: 1600,
      reportTime: '12-24 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Highly specific diagnostic biomarker for early detection and severity prognosis of Rheumatoid Arthritis.'
    },
    {
      id: 'pt-inr',
      name: 'PT / INR (Prothrombin Time)',
      category: 'blood',
      price: 250,
      originalPrice: 350,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (Citrate)',
      fastingRequired: 'No Fasting Required',
      description: 'Prothrombin Time and International Normalized Ratio evaluating blood coagulation and monitoring blood thinners.'
    },
    {
      id: 'widal',
      name: 'Widal Test (Typhoid Fever)',
      category: 'blood',
      price: 120,
      originalPrice: 120,
      reportTime: '3-4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Serological slide agglutination test for Salmonella typhi and paratyphi antibodies causing enteric fever.'
    },
    {
      id: 'typhidot',
      name: 'Typhidot IgG / IgM',
      category: 'blood',
      price: 450,
      originalPrice: 550,
      reportTime: '4-6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Rapid qualitative antibody test for early (IgM) and past/subacute (IgG) typhoid fever detection.'
    },
    {
      id: 'malaria-antigen',
      name: 'Malaria Antigen (Rapid Test)',
      category: 'blood',
      price: 300,
      originalPrice: 400,
      reportTime: '2-4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Rapid antigen detection for Plasmodium vivax and Plasmodium falciparum in acute fever cases.'
    },
    {
      id: 'malaria-parasite',
      name: 'Malaria Parasite (MP Smear Examination)',
      category: 'blood',
      price: 120,
      originalPrice: 120,
      reportTime: '2-4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Peripheral blood smear examination under microscope for direct visual detection of malarial parasites.'
    },
    {
      id: 'hiv-rapid',
      name: 'HIV 1 & 2 Rapid (Confidential)',
      category: 'blood',
      price: 250,
      originalPrice: 350,
      reportTime: '3-4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Confidential rapid chromatographic immunoassay for detection of antibodies to HIV-1 and HIV-2.'
    },
    {
      id: 'hba1c',
      name: 'HbA1c (Glycated Hemoglobin)',
      category: 'diabetes',
      price: 200,
      originalPrice: 300,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (EDTA)',
      fastingRequired: 'No Fasting Required',
      description: 'Standard glycated hemoglobin test calculating the past 3 months average blood sugar control.'
    },
    {
      id: 'hba1c-hplc',
      name: 'HbA1c (HPLC Advanced Gold Standard)',
      category: 'diabetes',
      price: 350,
      originalPrice: 450,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (EDTA)',
      fastingRequired: 'No Fasting Required',
      description: 'NGSP-certified High Performance Liquid Chromatography HbA1c with Estimated Average Glucose (eAG).'
    },
    {
      id: 'hcv',
      name: 'HCV (Hepatitis C Rapid Screening)',
      category: 'blood',
      price: 380,
      originalPrice: 480,
      reportTime: '4-6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Rapid qualitative test for Hepatitis C virus antibodies to screen and protect liver health.'
    },
    {
      id: 'blood-group',
      name: 'Blood Group (ABO & Rh Typing)',
      category: 'blood',
      price: 100,
      originalPrice: 100,
      reportTime: '2 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting Required',
      description: 'Definitive determination of ABO blood group and Rh factor (positive/negative) with emergency card.'
    },
    {
      id: 'beta-hcg',
      name: 'Beta hCG (Pregnancy & Hormone Marker)',
      category: 'blood',
      price: 500,
      originalPrice: 600,
      reportTime: '4-6 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Quantitative Beta Human Chorionic Gonadotropin blood test for pregnancy confirmation and monitoring.'
    },
    {
      id: 'serum-ige-total',
      name: 'Serum IgE Total (Allergy Marker)',
      category: 'blood',
      price: 500,
      originalPrice: 600,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Measures total circulating Immunoglobulin E to diagnose allergic asthma, rhinitis, eczema, or urticaria.'
    },
    {
      id: 'hscrp',
      name: 'hsCRP (High Sensitivity CRP - Cardiac Risk)',
      category: 'heart',
      price: 500,
      originalPrice: 600,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'High-sensitivity cardiovascular marker evaluating low-grade arterial wall inflammation and cardiac risk.'
    },
    {
      id: 'iron-panel-basic',
      name: 'Iron Panel Basic (Iron + TIBC)',
      category: 'blood',
      price: 600,
      originalPrice: 700,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'Morning Fasting Recommended',
      description: 'Measures Serum Iron, Total Iron Binding Capacity (TIBC), and Transferrin Saturation for anemia evaluation.'
    },
    {
      id: 'psa-total',
      name: 'PSA Total (Prostate Specific Antigen)',
      category: 'blood',
      price: 500,
      originalPrice: 600,
      reportTime: '6-8 Hours',
      sampleType: 'Blood (Serum)',
      fastingRequired: 'No Fasting Required',
      description: 'Key screening biomarker for men to assess prostate health, benign hyperplasia (BPH), and early detection.'
    },
    {
      id: 'serum-creatinine',
      name: 'Serum Creatinine',
      category: 'liver-kidney',
      price: 200,
      originalPrice: 250,
      reportTime: '4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting',
      description: 'Key waste-filtration marker in blood used to track renal performance.'
    },
    {
      id: 'uric-acid',
      name: 'Serum Uric Acid',
      category: 'liver-kidney',
      price: 200,
      originalPrice: 250,
      reportTime: '4 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting',
      description: 'Primary diagnostic test for joint pain, gout arthritis, and renal stone risk.'
    },
    {
      id: 'electrolytes',
      name: 'Serum Electrolytes (Na+, K+, Cl-)',
      category: 'blood',
      price: 450,
      originalPrice: 600,
      reportTime: '6 Hours',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting',
      description: 'Checks hydration, acid-base balance, sodium, potassium, and chloride.'
    },
    {
      id: 'dengue-ns1',
      name: 'Dengue NS1 Antigen & Antibody Duo',
      category: 'blood',
      price: 800,
      originalPrice: 1200,
      reportTime: '4 Hours Rapid',
      sampleType: 'Blood',
      fastingRequired: 'No Fasting',
      description: 'Rapid diagnostic test for Dengue fever detection from day 1 of symptoms.'
    }
  ]
};

window.diagnosticData = diagnosticData;
